wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.6.5
    cli_version: 0.15.11
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701775277.57285
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      4: 3.6.5
      5: 0.15.11
      8:
      - 1
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
